version: "3"
services:
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=devRoasted
      - POSTGRES_PASSWORD=roastPass
      - POSTGRES_DB=roastedcoffe
    ports:
      - "5432:5432"
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on:
      - db
    environment:
      - PGUSER=devRoasted
      - PGHOST=db
      - PGDATABASE=roastedcoffe
      - PGPASSWORD=roastPass
      - PGPORT=5432
    ports:
      - "5000:5000"
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
